pipeline {
    agent {
        docker {
            image 'maven:3.9.8-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('build') {
            steps {
                echo 'Building worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }

        stage('test') {
            steps {
                echo 'Running unit tests on worker app'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('package') {
            steps {
                echo 'Packaging worker app into a JAR file'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            echo 'The job is complete'
        }
    }
}
